<!-- custom about with chatbox create by voitgxd -->
<link rel="stylesheet" href="http://7xnq6l.com1.z0.glb.clouddn.com/style.css">
<script type="text/javascript" src="http://7xnq6l.com1.z0.glb.clouddn.com/jquery-1.9.0.min.js"></script>
<script type="text/javascript" src="https://cdn.socket.io/socket.io-1.3.7.js"></script>
<script type="text/javascript" src="http://7xnq6l.com1.z0.glb.clouddn.com/client-chat-box.js"></script>