<!-- custom about with chatbox create by voitgxd -->
<!-- <link rel="stylesheet" href="http://7xnq6l.com1.z0.glb.clouddn.com/style.css">-->
<!-- <script type="text/javascript" src="http://7xnq6l.com1.z0.glb.clouddn.com/jquery-1.9.0.min.js"></script>-->
<!-- <script type="text/javascript" src="http://7xnq6l.com1.z0.glb.clouddn.com/socket.io-1.3.7-chatbox.js"></script>-->
<!-- <script type="text/javascript" src="http://7xnq6l.com1.z0.glb.clouddn.com/client-chatbox.js"></script>-->

<script type="text/javascript">chatboxRoomHash = '0db3135d83810c904c13717aa078f830';</script>
<link rel="stylesheet" href="http://lifeislikeaboat.com:2007/client.css">
<script src="https://code.jquery.com/jquery-1.9.0.min.js"></script>
<script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
<script src="http://lifeislikeaboat.com:2007/client.js"></script>