<!-- custom about with chatbox create by voitgxd -->
<script type="text/javascript">chatboxRoomHash = '0db3135d83810c904c13717aa078f830';</script>
<link rel="stylesheet" href="http://7xnq6l.com1.z0.glb.clouddn.com/client_20160218.css">
<script type="text/javascript" src="http://7xnq6l.com1.z0.glb.clouddn.com/jquery-1.9.0.min.js"></script>
<script type="text/javascript" src="http://7xnq6l.com1.z0.glb.clouddn.com/socket.io-1.4.5_20160218.js"></script>
<script type="text/javascript" src="http://7xnq6l.com1.z0.glb.clouddn.com/client_20160218.js"></script>
